/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ListSearch: typeof import('./src/components/list/search/ListSearch.vue')['default']
    ListSearchItem: typeof import('./src/components/list/search/ListSearchItem.vue')['default']
    ListTable: typeof import('./src/components/list/table/ListTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeInput: typeof import('./src/components/list/search/SeInput.vue')['default']
    SeSelect: typeof import('./src/components/list/search/SeSelect.vue')['default']
  }
}
